### ISSUE TITLE
Wallpaper keeps getting fullscreen

### ISSUE THREAD

**Issue by itsfolf** [Gudov/wallpaper#1]
First of all, hello, and thanks for this repo! 
I've been testing out with it and I've been running into a problem where if I minimize all windows and get to the desktop, the wallpaper will get fullscreen, and sometimes even flicker between normal and fullscreen, in any chance have you come with a solution for this?

**Comment by Gudov** [comment]
I'm afraid not

**Comment by itsfolf** [comment]
Didn't even remember what this was lmao
